### ISSUE TITLE
Cant follow the tutorial

### ISSUE THREAD

**Issue by SimonRiemertzon** [leopug/NewMapTypesTutorial#1]
Hello! 

This seems like exactly what I need but I get bunch of problems as soon as I try to follow your tutorial. Mostly it is
Cannot find 'MKStandardMapConfiguration' in scope
Cannot find 'MKHybridMapConfiguration' in scope
and similar MK related things. 

Is there a. step in the tutorial that you forgot to add?

I have tried to clean the build folder, restarted and checking for typos. But I cant find the problem.

**Comment by leopug** [comment]
Hey Simon, this is just for iOS 16+. Are you using a lower version?

**Comment by SimonRiemertzon** [comment]
Ah yes... that is the problem of course. I have to use 15.5 for what I'm trying to do. Thank you for clearing that up!
